// Auto-generated by scripts/exportAbis.ts
// Do not edit by hand.

export const ADDRESSES = {
  bBTC: "0x7C8bE6Cf901468aECdEfbA49Bd71eE9bC7caD87A",
  WBTC: "0xecE1e95462432Ac8F972E1E223e0fCf21a2dE0fe",
  USDC: "0xc911d344C12B611E1B160a9916B2a29b12f81eDc",
  LendingPool: "0x91ecf55Bc7d1aB6E971B8Ee0184F937Bac1Ba8F9",
  LeaseManager: "0x595055056b44f8cFC84a55bdB59Cd4dFAf277d10",
  BTCOracle: "0x41b9e12589ADA499b9c7dc85eFC40922bCD3A69d",
  GPUOracle: "0xCC42924Bc04e1AdF4E035F6ce81ed8fa7a797F67"
} as const;
