name: Oracle Updater (Core Testnet)

on:
  # schedule:
  #   - cron: "*/15 * * * *"  # every 15 minutes - DISABLED
  workflow_dispatch:

jobs:
  update-oracles:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          cd frontend && npm install

      - name: Build contracts
        run: npx hardhat compile

      - name: Push BTC price to SignedBTCOracle
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ORACLE_SIGNER_PRIVATE_KEY: ${{ secrets.ORACLE_SIGNER_PRIVATE_KEY }}
          CORE_TESTNET_RPC: ${{ secrets.CORE_TESTNET_RPC }}
          CORE_TESTNET_CHAIN_ID: ${{ secrets.CORE_TESTNET_CHAIN_ID }}
          PRICE: ${{ secrets.BTC_PRICE_USD }}
          VALID_MINUTES: ${{ secrets.BTC_VALID_MINUTES }}
        run: |
          npx hardhat run scripts/updateBtcPrice.ts --network coretestnet

      - name: Push GPU price/stock
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ORACLE_SIGNER_PRIVATE_KEY: ${{ secrets.ORACLE_SIGNER_PRIVATE_KEY }}
          CORE_TESTNET_RPC: ${{ secrets.CORE_TESTNET_RPC }}
          CORE_TESTNET_CHAIN_ID: ${{ secrets.CORE_TESTNET_CHAIN_ID }}
          GPU: ${{ secrets.GPU_TYPE }}
          PRICE: ${{ secrets.GPU_PRICE_USD_PER_HOUR }}
          AVAILABLE: ${{ secrets.GPU_AVAILABLE }}
          STOCK: ${{ secrets.GPU_STOCK }}
          VALID_MINUTES: ${{ secrets.GPU_VALID_MINUTES }}
        run: |
          npx hardhat run scripts/updateGpuPrice.ts --network coretestnet

      - name: Log addresses
        run: |
          node -e 'console.log(require("./deployment-info.json"))'
